version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8081:80" # local:container
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sinfisthebest
      MYSQL_DATABASE: sinfpages
    volumes:
      - ./private/pages.sql:/docker-entrypoint-initdb.d/pages.sql
